// Main entry point — re-export models, sequelize instance, and utilities
export {
  sequelize,
  User,
  UserRecord,
  UserDetails,
  Lawyer,
  Junior,
  LegalArea,
  Contract,
  Query,
  QueryResponse,
  Slot,
  RylawChat,
  File,
  CompanyRegistration,
  CompanyLawyer,
  Task,
  StateData,
  District,
  DcAdvCase,
  DcCaseDetail,
  DcComplex,
  DcCourt,
  CallLog,
  Message,
  MessageReply,
  MessageDelete,
  MessageStatus,
  ChatGroup,
  GroupMember,
  Workspace,
  WorkspaceMember,
  Folder,
  FileShare,
} from './models';

export { TestConnection } from './config/db';
