// Main entry point — re-export models, sequelize instance, and utilities
export {
  sequelize,
  User, UserAttributes, UserCreationAttributes,
  UserRecord, UserRecordAttributes, UserRecordCreationAttributes,
  UserDetails,
  Lawyer,
  Junior,
  LegalArea, LegalAreaAttributes, LegalAreaCreationAttributes,
  Contract,
  Query, QueryAttributes, QueryCreationAttributes,
  QueryResponse, QueryResponseAttributes, QueryResponseCreationAttributes,
  Slot, SlotAttributes, SlotCreationAttributes,
  RylawChat, RylawChatAttributes, RylawChatCreationAttributes,
  File, FileAttributes, FileCreationAttributes,
  CompanyRegistration,
  CompanyLawyer,
  Task,
  StateData,
  District,
  DcAdvCase,
  DcCaseDetail,
  DcComplex,
  DcCourt,
  CallLog, CallLogAttributes, CallLogCreationAttributes,
  Message, MessageAttributes, MessageCreationAttributes,
  MessageReply,
  MessageDelete,
  MessageStatus,
  ChatGroup,
  GroupMember,
  Workspace,
  WorkspaceMember,
  Folder,
  FileShare,
} from './models';

export { TestConnection } from './config/db';
